name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include: # @todo source this from JSON?
          - name: Linux, x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: Linux, x86
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - name: Linux, aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - name: Linux, armv7
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          - name: Windows, x64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
          - name: Windows, x86
            os: windows-latest
            target: i686-pc-windows-msvc
            suffix: .exe
          - name: macOS, x86_64
            os: macos-latest
            target: x86_64-apple-darwin
          - name: macOS, aarch64
            os: macos-latest
            target: aarch64-apple-darwin
        # platform:
        #   - name: Linux
        #     os: ubuntu-latest
        #     target: [x86_64, x86, aarch64, armv7]
        #   - name: macOS
        #     os: macos-latest
        #     target: [x86_64, aarch64]
        #   - name: Windows
        #     os: windows-latest
        #     target: [x64, x86]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release

      - name: Rename binary
        run: |
          mkdir -p artifacts
          cp \
            target/release/ctrl-z${{ matrix.suffix }} \
            artifacts/ctrl-z-${{ matrix.target }}${{ matrix.suffix }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ctrl-z-${{ matrix.target }}
          path: artifacts/ctrl-z-${{ matrix.target }}
