name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux, x86_64
            os: ubuntu-latest
            target: x86_64
            suffix: ""
          - name: Linux, x86
            os: ubuntu-latest
            target: x86
            suffix: ""
          - name: Linux, aarch64
            os: ubuntu-latest
            target: aarch64
            suffix: ""
          - name: Linux, armv7
            os: ubuntu-latest
            target: armv7
            suffix: ""
          - name: macOS, x86_64
            os: macos-latest
            target: x86_64
            suffix: ""
          - name: macOS, aarch64
            os: macos-latest
            target: aarch64
            suffix: ""
          - name: Windows, x64
            os: windows-latest
            target: x86
            # suffix: ".exe"
          - name: Windows, x86
            os: windows-latest
            target: x64
            # suffix: ".exe"
        # platform:
        #   - name: Linux
        #     os: ubuntu-latest
        #     target: [x86_64, x86, aarch64, armv7]
        #   - name: macOS
        #     os: macos-latest
        #     target: [x86_64, aarch64]
        #   - name: Windows
        #     os: windows-latest
        #     target: [x64, x86]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release

      - name: Rename binary
        run: |
          mkdir -p artifacts
          cp \
            target/${{ matrix.target }}/release/ctrl-z \
            artifacts/ctrl-z-${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ctrl-z-${{ matrix.target }}
          path: artifacts/ctrl-z-${{ matrix.target }}
